name: Deploy

on:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Deploy to heroku   
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "templata"
          heroku_email: "kaypee90@yahoo.com"